# Generated by Django 6.0.4 on 2026-04-27 14:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Заголовок (рус)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Заголовок (англ)')),
                ('content_ru', models.TextField(verbose_name='Текст (рус)')),
                ('content_en', models.TextField(verbose_name='Текст (англ)')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Название (рус)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Название (англ)')),
                ('description_ru', models.TextField(verbose_name='Описание (рус)')),
                ('description_en', models.TextField(verbose_name='Описание (англ)')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('area', models.IntegerField(verbose_name='Площадь (м²)')),
                ('project_type', models.CharField(choices=[('apartment', 'Квартира'), ('house', 'Дом'), ('hotel', 'Отель'), ('resort', 'База отдыха')], default='apartment', max_length=20)),
                ('style', models.CharField(choices=[('scandi', 'Сканди'), ('minimalism', 'Минимализм'), ('loft', 'Лофт'), ('classic', 'Классика')], default='minimalism', max_length=20)),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Главное изображение')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('contact_method', models.CharField(choices=[('telegram', 'Написать в Telegram'), ('call', 'Позвонить по телефону')], default='telegram', max_length=20)),
                ('consent', models.BooleanField(default=True, verbose_name='Согласие на обработку')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('processed', 'Обработана')], default='new', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name_ru', models.CharField(blank=True, default='', max_length=200, verbose_name='Имя клиента (рус)')),
                ('client_name_en', models.CharField(blank=True, default='', max_length=200, verbose_name='Имя клиента (англ)')),
                ('text_ru', models.TextField(verbose_name='Текст отзыва (рус)')),
                ('text_en', models.TextField(verbose_name='Текст отзыва (англ)')),
                ('project_ru', models.CharField(blank=True, default='', max_length=200, verbose_name='Название проекта (рус)')),
                ('project_en', models.CharField(blank=True, default='', max_length=200, verbose_name='Название проекта (англ)')),
                ('rating', models.IntegerField(default=5, verbose_name='Рейтинг (1-5)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reviews/')),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Название (рус)')),
                ('name_en', models.CharField(max_length=200, verbose_name='Название (англ)')),
                ('description_ru', models.TextField(verbose_name='Описание (рус)')),
                ('description_en', models.TextField(verbose_name='Описание (англ)')),
                ('duration_ru', models.CharField(blank=True, max_length=100, verbose_name='Срок (рус)')),
                ('duration_en', models.CharField(blank=True, max_length=100, verbose_name='Срок (англ)')),
                ('examples_ru', models.TextField(blank=True, verbose_name='Примеры (рус)')),
                ('examples_en', models.TextField(blank=True, verbose_name='Примеры (англ)')),
                ('icon', models.FileField(blank=True, null=True, upload_to='services/', verbose_name='Иконка (SVG)')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
