# Generated by Django 6.0.4 on 2026-04-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='request',
            name='question',
            field=models.TextField(blank=True, null=True, verbose_name='Вопрос'),
        ),
    ]
