# Generated by Django 6.0.4 on 2026-04-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_request_email_request_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Изображение баннера')),
                ('banner_title_ru', models.CharField(blank=True, default='', max_length=200, verbose_name='Заголовок баннера (рус)')),
                ('banner_title_en', models.CharField(blank=True, default='', max_length=200, verbose_name='Заголовок баннера (англ)')),
                ('banner_subtitle_ru', models.CharField(blank=True, default='', max_length=200, verbose_name='Подзаголовок баннера (рус)')),
                ('banner_subtitle_en', models.CharField(blank=True, default='', max_length=200, verbose_name='Подзаголовок баннера (англ)')),
                ('quote_text_ru', models.TextField(blank=True, default='', verbose_name='Текст цитаты (рус)')),
                ('quote_text_en', models.TextField(blank=True, default='', verbose_name='Текст цитаты (англ)')),
                ('quote_author_ru', models.CharField(blank=True, default='', max_length=200, verbose_name='Автор цитаты (рус)')),
                ('quote_author_en', models.CharField(blank=True, default='', max_length=200, verbose_name='Автор цитаты (англ)')),
            ],
            options={
                'verbose_name': 'Настройка сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
