# Generated by Django 6.0.4 on 2026-04-27 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='promo_banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Изображение промо-баннера'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='promo_text_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Текст промо-баннера (англ)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='promo_text_ru',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Текст промо-баннера (рус)'),
        ),
    ]
