# Generated by Django 6.0.4 on 2026-04-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_sitesettings_promo_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Фото руководителя (О бюро)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_name_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Имя руководителя (англ)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_name_ru',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Имя руководителя (рус)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_position_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Должность (англ)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_position_ru',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Должность (рус)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_quote_en',
            field=models.TextField(blank=True, default='', verbose_name='Цитата руководителя (англ)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_quote_ru',
            field=models.TextField(blank=True, default='', verbose_name='Цитата руководителя (рус)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_text_en',
            field=models.TextField(blank=True, default='', verbose_name='Основной текст (англ)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_text_ru',
            field=models.TextField(blank=True, default='', verbose_name='Основной текст (рус)'),
        ),
    ]
