# Generated by Django 6.0.4 on 2026-04-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_sitesettings_about_image_sitesettings_about_name_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Фото руководителя')),
                ('name_ru', models.CharField(blank=True, default='', max_length=200, verbose_name='Имя (рус)')),
                ('name_en', models.CharField(blank=True, default='', max_length=200, verbose_name='Имя (англ)')),
                ('position_ru', models.CharField(blank=True, default='', max_length=200, verbose_name='Должность (рус)')),
                ('position_en', models.CharField(blank=True, default='', max_length=200, verbose_name='Должность (англ)')),
                ('quote_ru', models.CharField(blank=True, default='', max_length=200, verbose_name='Цитата (рус)')),
                ('quote_en', models.CharField(blank=True, default='', max_length=200, verbose_name='Цитата (англ)')),
                ('text_ru', models.TextField(blank=True, default='', verbose_name='Текст (рус)')),
                ('text_en', models.TextField(blank=True, default='', verbose_name='Текст (англ)')),
            ],
            options={
                'verbose_name': 'О бюро',
                'verbose_name_plural': 'О бюро',
            },
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='about_image',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='about_name_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='about_name_ru',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='about_position_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='about_position_ru',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='about_quote_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='about_quote_ru',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='about_text_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='about_text_ru',
        ),
    ]
