# Generated by Django 6.0.4 on 2026-05-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_aboutsettings_remove_sitesettings_about_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_ru', models.CharField(max_length=255, verbose_name='Адрес (рус)')),
                ('address_en', models.CharField(max_length=255, verbose_name='Адрес (англ)')),
                ('address_map_url', models.URLField(blank=True, verbose_name='Ссылка на карту')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон (для отображения)')),
                ('phone_raw', models.CharField(blank=True, max_length=20, verbose_name='Телефон для ссылки (без пробелов)')),
                ('inn_ru', models.CharField(max_length=255, verbose_name='ИНН (рус)')),
                ('inn_en', models.CharField(max_length=255, verbose_name='ИНН (англ)')),
            ],
            options={
                'verbose_name': 'Настройка футера',
                'verbose_name_plural': 'Настройки футера',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название (VK, YouTube и т.д.)')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('icon', models.CharField(max_length=200, verbose_name='Путь к иконке (например /icons/vk.svg)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Социальная ссылка',
                'verbose_name_plural': 'Социальные ссылки',
                'ordering': ['order'],
            },
        ),
    ]
