# Generated by Django 6.0.4 on 2026-05-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_footersettings_sociallink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='icon',
            field=models.FileField(help_text='Загрузите SVG‑файл', upload_to='social_icons/', verbose_name='Иконка (SVG)'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
