# Generated by Django 6.0.4 on 2026-05-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_sociallink_icon_alter_sociallink_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_ru', models.CharField(max_length=255, verbose_name='Адрес (рус)')),
                ('address_en', models.CharField(max_length=255, verbose_name='Адрес (англ)')),
                ('address_map_url', models.URLField(blank=True, verbose_name='Ссылка на карту')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон (для отображения)')),
                ('phone_raw', models.CharField(blank=True, max_length=20, verbose_name='Телефон для ссылки (без пробелов)')),
                ('legal_name_ru', models.CharField(max_length=255, verbose_name='Юридическое название (рус)')),
                ('legal_name_en', models.CharField(max_length=255, verbose_name='Юридическое название (англ)')),
                ('inn_ru', models.CharField(max_length=100, verbose_name='ИНН (рус)')),
                ('inn_en', models.CharField(max_length=100, verbose_name='ИНН (англ)')),
            ],
            options={
                'verbose_name': 'Контактная настройка',
                'verbose_name_plural': 'Контактные настройки',
            },
        ),
    ]
