# Generated by Django 6.0.4 on 2026-05-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_privacypolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services_banner/', verbose_name='Фото баннера')),
                ('text_ru', models.CharField(max_length=255, verbose_name='Текст баннера (рус)')),
                ('text_en', models.CharField(max_length=255, verbose_name='Текст баннера (англ)')),
            ],
            options={
                'verbose_name': 'Баннер (Услуги)',
                'verbose_name_plural': 'Баннер (Услуги)',
            },
        ),
    ]
