# Generated by Django 6.0.4 on 2026-05-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_servicesbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ru', models.TextField(blank=True, verbose_name='Текст цитаты (ru)')),
                ('text_en', models.TextField(blank=True, verbose_name='Текст цитаты (en)')),
                ('author_ru', models.CharField(blank=True, max_length=255, verbose_name='Автор цитаты (ru)')),
                ('author_en', models.CharField(blank=True, max_length=255, verbose_name='Автор цитаты (en)')),
            ],
            options={
                'verbose_name': 'Цитата для страницы "Отзывы"',
                'verbose_name_plural': 'Цитата для страницы "Отзывы"',
            },
        ),
    ]
