# Generated by Django 6.0.4 on 2026-05-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_reviewquote'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_ru', models.TextField(verbose_name='Вопрос (рус)')),
                ('question_en', models.TextField(verbose_name='Вопрос (англ)')),
                ('answer_ru', models.TextField(verbose_name='Ответ (рус)')),
                ('answer_en', models.TextField(verbose_name='Ответ (англ)')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='team/', verbose_name='Фото')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Имя (рус)')),
                ('name_en', models.CharField(max_length=200, verbose_name='Имя (англ)')),
                ('position_ru', models.CharField(max_length=200, verbose_name='Должность (рус)')),
                ('position_en', models.CharField(max_length=200, verbose_name='Должность (англ)')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники (другие)',
                'ordering': ['order'],
            },
        ),
    ]
