# Generated by Django 6.0.4 on 2026-05-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_faq_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsettings',
            name='page_text_en',
            field=models.TextField(blank=True, default='', verbose_name='Текст на странице "О бюро" (англ)'),
        ),
        migrations.AddField(
            model_name='aboutsettings',
            name='page_text_ru',
            field=models.TextField(blank=True, default='', verbose_name='Текст на странице "О бюро" (рус)'),
        ),
    ]
