# Generated by Django 6.0.4 on 2026-05-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_aboutsettings_page_text_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='full_content_en',
            field=models.TextField(blank=True, verbose_name='Полный текст новости (англ)'),
        ),
        migrations.AddField(
            model_name='news',
            name='full_content_ru',
            field=models.TextField(blank=True, verbose_name='Полный текст новости (рус)'),
        ),
    ]
