# Generated by Django 6.0.4 on 2026-05-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_news_full_content_en_news_full_content_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='details_en',
            field=models.TextField(blank=True, default='', verbose_name='Детали проекта (англ)'),
        ),
        migrations.AddField(
            model_name='project',
            name='details_ru',
            field=models.TextField(blank=True, default='', verbose_name='Детали проекта (рус)'),
        ),
        migrations.AddField(
            model_name='project',
            name='full_description_en',
            field=models.TextField(blank=True, default='', verbose_name='Полное описание (англ)'),
        ),
        migrations.AddField(
            model_name='project',
            name='full_description_ru',
            field=models.TextField(blank=True, default='', verbose_name='Полное описание (рус)'),
        ),
        migrations.AddField(
            model_name='project',
            name='gallery',
            field=models.JSONField(blank=True, default=list, verbose_name='Галерея (массив URL изображений)'),
        ),
        migrations.AddField(
            model_name='project',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Второе изображение (730x365)'),
        ),
        migrations.AddField(
            model_name='project',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Третье изображение (485x380)'),
        ),
        migrations.AddField(
            model_name='project',
            name='participants_en',
            field=models.TextField(blank=True, default='', verbose_name='Участники проекта (англ)'),
        ),
        migrations.AddField(
            model_name='project',
            name='participants_ru',
            field=models.TextField(blank=True, default='', verbose_name='Участники проекта (рус)'),
        ),
    ]
