# Generated by Django 6.0.4 on 2026-05-05 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_request_progress_request_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='area',
            field=models.IntegerField(blank=True, null=True, verbose_name='Площадь (м²)'),
        ),
        migrations.AddField(
            model_name='request',
            name='project_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип пространства'),
        ),
        migrations.AddField(
            model_name='request',
            name='style',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Стиль'),
        ),
    ]
