# Generated by Django 6.0.4 on 2026-05-05 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_request_area_request_project_type_request_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='progress',
        ),
        migrations.AlterField(
            model_name='request',
            name='area',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Площадь, м²'),
        ),
        migrations.AlterField(
            model_name='request',
            name='project_type',
            field=models.CharField(blank=True, choices=[('apartment', 'Квартира'), ('house', 'Жильё'), ('hotel', 'Отель'), ('resort', 'База отдыха')], max_length=20, null=True, verbose_name='Тип пространства'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('sent', 'Отправлен запрос'), ('discussed', 'Обсудили проект'), ('tz', 'Сформировано ТЗ'), ('in_progress', 'Проект в работе'), ('ready', 'Проект готов')], default='sent', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='request',
            name='style',
            field=models.CharField(blank=True, choices=[('scandi', 'Сканди'), ('minimalism', 'Минимализм'), ('loft', 'Лофт'), ('classic', 'Классика')], max_length=20, null=True, verbose_name='Стиль'),
        ),
    ]
