# Generated by Django 6.0.4 on 2026-05-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_request_progress_alter_request_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='review_submitted',
            field=models.BooleanField(default=False, verbose_name='Отзыв уже отправлен'),
        ),
    ]
