# Generated by Django 6.0.4 on 2026-05-11 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_news_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Главная(баннеры и цитаты)', 'verbose_name_plural': 'Главная(баннеры и цитаты)'},
        ),
        migrations.AlterModelOptions(
            name='sociallink',
            options={'ordering': ['order'], 'verbose_name': 'Социальная сети ссылка', 'verbose_name_plural': 'Социальные сети ссылки'},
        ),
    ]
